// Auto-generated by Supabase CLI. Do not edit manually.
// Regenerate after every migration: supabase gen types typescript --local > src/lib/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          created_at: string
        }
        Insert: {
          id: string
          display_name: string
          created_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          created_at?: string
        }
        Relationships: []
      }
      exercises: {
        Row: {
          id: string
          name: string
          category: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          category?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          category?: string | null
          created_by?: string | null
          created_at?: string
        }
        Relationships: []
      }
      workout_sessions: {
        Row: {
          id: string
          user_id: string
          started_at: string
          finished_at: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          started_at?: string
          finished_at?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          started_at?: string
          finished_at?: string | null
          notes?: string | null
          created_at?: string
        }
        Relationships: []
      }
      session_exercises: {
        Row: {
          id: string
          session_id: string
          exercise_id: string
          display_order: number
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          exercise_id: string
          display_order: number
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          exercise_id?: string
          display_order?: number
          created_at?: string
        }
        Relationships: []
      }
      set_entries: {
        Row: {
          id: string
          session_exercise_id: string
          user_id: string
          set_number: number
          weight_kg: number | null
          reps: number
          created_at: string
        }
        Insert: {
          id?: string
          session_exercise_id: string
          user_id: string
          set_number: number
          weight_kg?: number | null
          reps: number
          created_at?: string
        }
        Update: {
          id?: string
          session_exercise_id?: string
          user_id?: string
          set_number?: number
          weight_kg?: number | null
          reps?: number
          created_at?: string
        }
        Relationships: []
      }
      workout_templates: {
        Row: {
          id: string
          user_id: string
          name: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      workout_template_exercises: {
        Row: {
          id: string
          template_id: string
          exercise_id: string
          display_order: number
        }
        Insert: {
          id?: string
          template_id: string
          exercise_id: string
          display_order: number
        }
        Update: {
          id?: string
          template_id?: string
          exercise_id?: string
          display_order?: number
        }
        Relationships: []
      }
    }
    Views: Record<never, never>
    Functions: Record<never, never>
    Enums: Record<never, never>
  }
}
